### ISSUE TITLE
Copying only the URL when in the Chrome address bar

### ISSUE THREAD

**Issue by ammarhusain** [zaki-yama/copy-title-and-url-as-markdown#297]
I love this extension! It makes my workflow with Obsidian super seamless.

I do find that I would like to just copy the url of the page sometimes rather than as markdown with title. I would assume if I am just within the address bar of google Chrome it would copy just the URL. However it seems like the plugin gets activated even when I am trying to copy just the URL (using Cmd + C) rather than using the plugin for which my keyboard shortcut is Ctrl + C.

Is there I can make sure that the plugin does not get activated within Chrome's address bar with the generic copy shortcut?

**Comment by zaki-yama** [comment]
@ammarhusain 
Thanks for reporting the issue!
I understood you were facing the following problem:

1. Set the keyboard shortcut as Ctrl + C
2. Focus the address bar in Chrome
3. Press Cmd + C to copy the URL
4. Instead of normal copy, the chrome extension was activated and the URL and title was copied

Unfortunately I have no idea why it happens, and I don't think I can control this.
I'll investigate the related information but current workaround is to replace keyboard shortcut something other than Ctrl + C.

**Comment by ammarhusain** [comment]
Workaround works well! Thanks!

**Comment by zaki-yama** [comment]
I'm glad to hear that! I'll close this issue but feel free to send the feedback if you have any feature requests / problems 😄
